### ISSUE TITLE
Write up Genome sequencing information sections

### ISSUE THREAD

**Issue by joshamilton** [McMahonLab/GenAnnc#2]
We will need to redo analysis once SAGs have been decontaminated. In the meantime, write up the various manuscript sections that don't require any data.

**Comment by sstevens2** [comment]
I will work on this in the betI manuscript and the copy it over to the others when we are happy with it

**Comment by sstevens2** [comment]
@mcmahon-uw Can we take this info from the L06 or Trevor's paper for the SAGs and Rex's paper for the GFMs?

**Comment by sstevens2** [comment]
@sstevens2 look up recent SIGS paper with IMG for annotation and whatnot information

**Comment by sstevens2** [comment]
@mcmahon-uw Do you know where I can find sequencing info like.. 
How many reads/bp were generated with the sequencing?
What software was used to assemble the genomes?
What the minimum and average coverage was?

**Comment by mcmahon-uw** [comment]
No.... we might need to get this from Miranda and Tijana directly.  Based on the response I got from my earlier email, we will have to wait until they are back from vacay, July 20

On Jul 9, 2015, at 4:43 PM, Sarah Stevens <notifications@github.com<mailto:notifications@github.com>> wrote:


@mcmahon-uw<https://github.com/mcmahon-uw> Do you know where I can find sequencing info like..
How many reads/bp were generated with the sequencing?
What software was used to assemble the genomes?
What the minimum and average coverage was?

—
Reply to this email directly or view it on GitHub<https://github.com/McMahonLab/GenAnnc/issues/2#issuecomment-120152182>.

-------------------------------------------------------------------------------------
Katherine (Trina) McMahon, Professor
Goddess of Funkosity
Vilas Distinguished Achievement Professor
Departments of Civil and Environmental Engineering and Bacteriology
Co-Faculty Director, Delta Program (http://www.delta.wisc.edu)
University of Wisconsin - Madison, Madison, WI  53706-1691

Office:  5552 Microbial Sciences Building (MSB)
Lab:  5525 MSB
Website:  http://mcmahonlab.wisc.edu/

Google Scholar: https://scholar.google.com/citations?user=SaAIxywAAAAJ&hl=en
-------------------------------------------------------------------------------------

**Comment by sstevens2** [comment]
Josh completed for betIV's and can copy paste for others, checking for minor changes
